Repository Gooaein/GoojilGoojil-FE, pull requests merged in 2024-09, with the labels that each got.

#4 Feature/#3 - CustomizingPage 일부 구현 및 CI/CD Test -1
  .github/workflows/front-build.yaml
  package-lock.json
  package.json
  src/assets/images/cloudCustomizing/eyes/eyes1.png
  src/assets/images/cloudCustomizing/eyes/eyes2.png
  src/assets/images/cloudCustomizing/eyes/eyes3.png
  src/assets/images/cloudCustomizing/eyes/eyes4.png
  src/assets/images/cloudCustomizing/mouth/mouth1.png
  src/assets/images/cloudCustomizing/mouth/mouth2.png
  src/assets/images/cloudCustomizing/mouth/mouth3.png
  src/assets/images/cloudCustomizing/mouth/mouth4.png
  src/assets/images/cloudCustomizing/waterDrop/blue-waterDrop.png
  src/assets/images/cloudCustomizing/waterDrop/green-waterDrop.png
  src/assets/images/cloudCustomizing/waterDrop/pink-waterDrop.png
  src/assets/images/cloudCustomizing/waterDrop/white-waterDrop.png
  src/components/water-drop/WaterDropCharacterCustomizing.jsx
  src/components/water-drop/WaterDropCharacterCustomizing.module.css
  src/components/water-drop/components/Customizer.jsx
  src/components/water-drop/components/Customizer.module.css
  src/components/water-drop/components/WaterDrop.jsx
  src/components/water-drop/components/WaterDrop.module.css
  src/constants/waterDropContent.js
  src/pages/customize/customizingPage.jsx
  src/recoil/character-atoms.js
  src/router.jsx
Labels: ✨ Feature, 🙍규진

#6 Feature/#3 - 물방울 애니메이션 추가
  src/components/water-drop/components/WaterDrop.module.css
Labels: 🔨 Refactor, ✨ Feature, 🙍규진

#8 Feat/#7 - Stomp 연결 및 Header 실시간 이미지 처리 및 채팅방 구현
  package-lock.json
  package.json
  src/api/room/room.js
  src/api/stomp/stomp.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/components/ActiveUsers.jsx
  src/components/common/Header/components/ActiveUsers.module.css
  src/components/common/Header/components/ActiveUsersContainer.jsx
  src/components/common/Header/components/ActiveUsersContainer.module.css
  src/components/messages/ChatMessages.js
  src/components/messages/ChatMessages.module.css
  src/components/messages/FloatingMessage.js
  src/components/messages/FloatingMessages.module.css
  src/pages/chat/chattingPage.jsx
  src/pages/chat/chattingRoomPage.jsx
  src/pages/chat/chattingRoomPage.module.css
  src/recoil/chat-atoms.js
  src/router.jsx
  src/stomp/chat/chat-stomp.js
  src/stomp/chat/useChattingRoom.js
Labels: 🔨 Refactor, 🌏 Deploy, ✨ Feature, 🙍규진

#11 Feat/#7 - 질문 구름 구현 및 생명주기 설정 및 Input 구현
  .vscode/launch.json
  src/assets/images/chat/sendIcon.png
  src/components/chat/cloud/QuestionCloud.jsx
  src/components/chat/cloud/QuestionCloud.module.css
  src/components/chat/input/ChattingInput.jsx
  src/components/chat/input/ChattingInput.module.css
  src/components/common/Header/Header.jsx
  src/components/intro/components/CloudComponent.jsx
  src/components/intro/components/CloudComponent.module.css
  src/constants/questionLifeTime.js
  src/mocks/mockStompClient.js
  src/mocks/mockWebSocket.js
  src/pages/chat/chattingRoomPage.jsx
  src/pages/chat/chattingRoomPage.module.css
  src/stomp/chat/chat-stomp.js
  src/stomp/chat/useChattingRoom.js
  src/util/generateCloud.js
Labels: ⚙ Setting, 🔨 Refactor, ✨ Feature, 🙍규진

#15 Feat/#7 - 실시간 구름 기능 추가 및 기초 stomp 통신 연결
  package-lock.json
  package.json
  src/assets/images/chat/chatCloudImage.png
  src/components/chat/cloud/QuestionCloud.jsx
  src/components/chat/cloud/QuestionCloud.module.css
  src/components/chat/input/ChattingInput.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/Header.module.css
  src/components/common/Header/components/ActiveUsers.jsx
  src/components/common/Header/components/ActiveUsers.module.css
  src/components/common/Header/components/ActiveUsersContainer.jsx
  src/components/common/Header/components/ActiveUsersContainer.module.css
  src/pages/chat/chattingRoomPage.jsx
  src/pages/chat/chattingRoomPage.module.css
  src/stomp/chat/chat-stomp.js
  src/stomp/chat/useChattingRoom.js
  src/stomp/chat/useSockJSChattingRoom.js
  src/util/getRandomCloudPosition.js
Labels: 🔨 Refactor, ✨ Feature, 🙍규진

#23 Feature/#16 - Stomp 고도화 및 API Instance 추가 설정
  src/api/instance.js
  src/api/request.js
  src/api/room/room.js
  src/api/user/user.js
  src/components/chat/input/ChattingInput.jsx
  src/components/water-drop/components/Customizer.jsx
  src/context/StompContext.js
  src/index.js
  src/pages/chat/chattingRoomPage.jsx
  src/router.jsx
  src/stomp/chat/useChattingRoom.js
Labels: 🔨 Refactor, 🌏 Deploy, ✨ Feature, 🙍규진

#24 🚀 deploy: esLint 수정사항 반영 후 배포
  src/components/chat/cloud/QuestionCloud.jsx
  src/pages/chat/chattingRoomPage.jsx
Labels: ⚙ Setting, 🐞 BugFix, 🌏 Deploy

#25 🚀 deploy: esLint 수정사항 반영 후 배포
  src/components/water-drop/components/Customizer.jsx
Labels: ⚙ Setting, 🌏 Deploy, 🙍규진

#28 Feature/#27 - Cookie 값 설정을 통한 사용자 식별 기능 추가
  package-lock.json
  package.json
  src/api/instance.js
  src/context/StompContext.js
  src/hooks/useAuthCookies.js
Labels: 🔨 Refactor, 🌏 Deploy, ✨ Feature, 🙍규진

#30 Feat/#29 - 강연자 페이지 퍼블리싱
  src/components/room/roomComponent.jsx
  src/components/room/roomComponent.module.css
  src/pages/createRoom/createRoomPage.jsx
  src/pages/createRoom/createRoomPage.module.css
  src/pages/list/copy.png
  src/pages/list/roomListPage.jsx
  src/pages/list/roomListPage.module.css
  src/pages/speakerRoom/heart.png
  src/pages/speakerRoom/speakerRoomPage.jsx
  src/pages/speakerRoom/speakerRoomPage.module.css
  src/router.jsx
Labels: 🎨 Design, ✨ Feature, 🙍규진

#34 Feature/#27 - 구름 랜덤 위치 기능 구현
  src/components/chat/cloud/QuestionCloud.jsx
  src/components/chat/cloud/QuestionCloud.module.css
  src/context/StompContext.js
  src/pages/chat/chattingRoomPage.jsx
  src/pages/chat/chattingRoomPage.module.css
  src/stomp/chat/useChattingRoom.js
Labels: 🔨 Refactor, ✨ Feature, 🙍규진

#35 Feature/#27 - 카카오 로그인 구현 및, 방 만들기 페이지 수정
  src/api/instance.js
  src/api/interceptor.js
  src/api/room/room.js
  src/api/room/useRoom.js
  src/assets/images/logo/kakaoLoginLogo.png
  src/components/water-drop/components/Customizer.jsx
  src/pages/createRoom/createRoomPage.jsx
  src/pages/login/loginPage.jsx
  src/pages/login/loginPage.module.css
  src/recoil/room-atoms.js
  src/stomp/chat/useChattingRoom.js
Labels: 🎨 Design, 🔨 Refactor, ✨ Feature, 🙍규진
